#!/usr/bin/env python3
"""bootstrap_config.py — Auto-detect project structure and generate config.

Called by the orchestrator at Stage 1 when `.deepseek/deepseek-research.toml`
does not exist. Detects available source axes and writes sensible defaults.

Usage:
    python3 bootstrap_config.py [--project-dir /path/to/project] [--dry-run]
"""

from __future__ import annotations

import os
import sys
from pathlib import Path


def detect_axes(project_dir: Path) -> list[str]:
    """Detect which source axes are available based on project structure."""
    axes = ["web"]  # web is always available

    # Detect bibliography
    bib_indicators = ["bibliography", "bib", "references", "papers"]
    for indicator in bib_indicators:
        bib_path = project_dir / indicator
        if bib_path.is_dir() and any(bib_path.iterdir()):
            axes.append("bibliography")
            break

    # Detect codebase (Rust, Python, JS, Julia)
    code_indicators = [
        "Cargo.toml", "pyproject.toml", "setup.py", "setup.cfg",
        "package.json", "Project.toml", "go.mod", "CMakeLists.txt"
    ]
    for indicator in code_indicators:
        if (project_dir / indicator).exists():
            axes.append("codebase")
            break

    return axes


def detect_bibliography_path(project_dir: Path) -> str:
    """Detect the bibliography directory path."""
    candidates = ["bibliography", "bib", "references", "papers"]
    for c in candidates:
        if (project_dir / c).is_dir():
            return f"{c}/"
    return "bibliography/"


def generate_config(project_dir: str | Path = ".", dry_run: bool = False) -> str:
    """Generate a .deepseek/deepseek-research.toml config file.

    Returns the generated TOML string.
    """
    project_dir = Path(project_dir).resolve()
    axes = detect_axes(project_dir)
    bib_path = detect_bibliography_path(project_dir)

    config = f"""# deepseek-research configuration — auto-generated by bootstrap_config.py
# Edit this file to customize your research pipeline.

# Discovery axes: which sources to search
source_axes = {axes}

# Bibliography path (local corpus of PDFs and references)
bibliography_path = "{bib_path}"

# Where session reports are written
output_dir = "research-reports/"

# Session index for cross-session tracking
session_index = "deep-search-sessions.json"

# Persist web-discovered sources to local corpus
persist_sources = true

# Maximum sources per discovery axis
max_sources_per_axis = 30

# Saturation window: stop when this many consecutive sources add nothing new
saturation_window = 5

# Dual screening for bibliography axis (two independent screeners)
dual_screening = false

# Cohen's kappa threshold for inter-rater agreement warning
agreement_threshold = 0.60

# Protocol pre-registration: "local", "osf", or "none"
protocol_registry = "local"

# OSF credentials (only needed if protocol_registry = "osf")
osf_token = ""
osf_project_id = ""

# Meta-analysis: "auto" (trigger on >=3 quantitative sources), "always", or "never"
meta_analysis = "auto"

# Deep reading: process full source documents via RLM chunking
deep_reading = true

# Stakeholder review: prompt user for feedback on draft findings
stakeholder_review = false

# Living review: enable periodic update searches
living_review = false
surveillance_interval_days = 90

# Open-source clone directory for T5 deep reading
oss_clone_dir = "oss/"
"""

    if not dry_run:
        config_dir = project_dir / ".deepseek"
        config_dir.mkdir(parents=True, exist_ok=True)
        config_path = config_dir / "deepseek-research.toml"
        config_path.write_text(config, encoding="utf-8")
        print(f"Config written to {config_path}")
        print(f"Detected axes: {axes}")
        print(f"Bibliography path: {bib_path}")

    return config


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Bootstrap deepseek-research config")
    parser.add_argument("--project-dir", default=".", help="Project directory")
    parser.add_argument("--dry-run", action="store_true", help="Print config without writing")
    args = parser.parse_args()

    generate_config(args.project_dir, dry_run=args.dry_run)
